language: java
jdk: oraclejdk8

notifications:
  email: true
    on_success: always # default: change
    on_failure: always # default: always
    
cache:
  directories:
    - $HOME/.m2

script:
  mvn verify
