language: java
jdk: oraclejdk8

notifications:
  email:
    recipients:
      - mark.d.denner@gmail.com
    on_success: never # default: change
    on_failure: always # default: always
    
cache:
  directories:
    - $HOME/.m2

script:
  mvn verify
